dist: bionic
sudo: required
arch:
    - amd64
    - arm64
language: c

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -y libtommath-dev libgmp-dev libtfm-dev valgrind libtool-bin

before_script:
  - gem install coveralls-lcov
  - curl http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.11.orig.tar.gz | tar xz
  - export PATH=$PATH:`pwd`/lcov-1.11/bin
  - curl -s https://packagecloud.io/install/repositories/libtom/packages/script.deb.sh | sudo bash
  - sudo apt-get install libtfm1=0.13-5ubuntu1

matrix:
  fast_finish: true
branches:
  only:
    - master
    - develop
    - /^release\/.*$/

compiler:
  - gcc

script:
  - bash "${BUILDSCRIPT}" "${BUILDNAME}" "-DUSE_LTM -DLTM_DESC" "makefile V=1"        "${BUILDOPTIONS}" "-ltommath" &&
    bash "${BUILDSCRIPT}" "${BUILDNAME}" "-DUSE_TFM -DTFM_DESC" "makefile.shared V=1" "${BUILDOPTIONS}" "-ltfm"
env:
  - |
    BUILDNAME="STOCK"
    BUILDOPTIONS=" "
    BUILDSCRIPT=".ci/run.sh"
 
after_failure:
  - cat test_std.txt
  - cat test_err.txt
  - cat tv.txt

after_script:
  - cat gcc_1.txt
  - cat gcc_2.txt

notifications:
  irc: "chat.freenode.net#libtom-notifications"
